Repository AmoghM/SmartDate, pull requests merged in 2019-06, with the labels that each got.

#15 Added backfill print statement and fixed id extraction from folder name
  src/content-acquisition/tinder/data_extractor.py
  src/content-acquisition/tinder/phone_auth_token.py
Labels: bug

#19 Fix bug of lost of profile data, optimized backfill, removed globals
  src/content-acquisition/tinder/data_extractor.py
Labels: bug, enhancement

#18 Tinder aayushi
  .DS_Store
  config/tinder.yaml
  src/.DS_Store
  src/content-acquisition/.DS_Store
  src/content-acquisition/tinder/data_cleaner.py
Labels: enhancement

#22 Fixing backfill
  src/content-acquisition/tinder/data_extractor.py
Labels: bug
